# .github/workflows/ducke.yml

name: Distribute Binaries on Release 

## TODO: Uncomment this before merge
# on: [release]

## TODO: Remove this `on` section before merge
on:
  push:
    branches:
      - 'feat/create_distribution'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release]
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
      - uses: actions/checkout@v5
      - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }}
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }}
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ducke_linux_x86-84
          path: target/${{ matrix.BUILD_TARGET }}/ducke
